### ISSUE TITLE
Usersテーブルの作成

### ISSUE THREAD

**Issue by 10tealights** [10tealights/new_moon_wishes_app#11]
### TODO
- [x] Sorcery(Gem)の導入
- [x] Usersテーブルの作成
  - [x] 作成するカラム
    - [x] name (str, NOT NULL)
    - [x] account_id (str, NOT NULL)
    - [x] crypeted_password (str)
    - [x] salt (str)
  - [x] idについては予定を変更してシーケンスではなくUUIDを生成(セキュリティ対策のため)
  参考URLによればPostgreSQLでUUIDを生成できる拡張機能があるため、こちらを利用可

### 参考URL
+ Sorcery
https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication
+ UUID
https://railsguides.jp/active_record_postgresql.html#uuid
https://tech.mof-mof.co.jp/blog/rails-use-uuid/
