### ISSUE TITLE
ゲストログインができる

### ISSUE THREAD

**Issue by 10tealights** [10tealights/new_moon_wishes_app#47]
### TODO
- [x] guest_sessions_controller.rbの作成
- [x] ルーティングの設定(guest_sessions : `create`)
- [x] Userモデルにゲスト用アカウント作成メソッドを追加
※ゲストアカウントはひとつではなく、都度ランダム文字列によって生成されるものとする。
- [x] guest_sessions#createアクション追加
- [x] 対応するリンクをビューファイルに追加

### 参考URL
https://blog.aiandrox.com/posts/tech/2021/03/13/
